name: lecture_room_allocator
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^3.0.5
  fl_chart: ^0.40.6 # Replace with the latest compatible version
  google_fonts: ^6.1.0
  web: any
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  js: ^0.7.2
  intl: ^0.20.2
  cloud_firestore: ^5.6.7 # Add the latest version of cloud_firestore 
  firebase_remote_config: ^5.4.3
  firebase_analytics: ^11.4.5
  firebase_storage: ^12.4.5
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_crashlytics: ^4.0.0 # Replace with the latest compatible version
  flutter_bloc: ^9.1.1
  # flutter_icons: ^1.1.0
  font_awesome_flutter: ^10.7.0
  feather_icons: ^1.2.0
  google_maps_flutter: ^2.5.0
  freezed_annotation: ^2.4.1
  injectable: ^2.5.0
  dartz: ^0.10.1
dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.7
flutter: 
  uses-material-design: true
assets:
    - lib/presentation/student_dashboard/widgets/attendance_stats_widget.dart
    - lib/presentation/student_dashboard/widgets/notification_card_widget.dart
    - lib/presentation/student_dashboard/widgets/venue_map_widget.dart