// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoURddxtK4TaMEObowqxM5Q_HMPS1d4Cg',
    appId: '1:154152922053:web:24d9be81213a34a873b9ac',
    messagingSenderId: '154152922053',
    projectId: 'campus-venue-navigator',
    authDomain: 'campus-venue-navigator.firebaseapp.com',
    storageBucket: 'campus-venue-navigator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDParFrsIkJhJcpN3KyfpVG2ynin9QJGcQ',
    appId: '1:154152922053:android:25c6bc8a0f350b6073b9ac',
    messagingSenderId: '154152922053',
    projectId: 'campus-venue-navigator',
    storageBucket: 'campus-venue-navigator.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoURddxtK4TaMEObowqxM5Q_HMPS1d4Cg',
    appId: '1:154152922053:web:a3b65f805f5192b273b9ac',
    messagingSenderId: '154152922053',
    projectId: 'campus-venue-navigator',
    authDomain: 'campus-venue-navigator.firebaseapp.com',
    storageBucket: 'campus-venue-navigator.firebasestorage.app',
  );
}
